- become: yes
  hosts: all
  name: grafana-install

  vars:
    dependances:
      - apt-transport-https
      - software-properties-common
      - wget

  tasks:
    - name: Création de l'utilisateur Grafana
      user:
        name: grafana
        group: sudo

    - name: Installation des dépendances
      apt:
        name: "{{ item }}"
      loop: "{{ dependances }}"

    - name: Installation dernière release OSS de grafana 1/2
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Installation dernière release OSS de grafana 2/2
      command : echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

    - name: Mise à jour des dépôts
      apt:
        update_cache: true
        force_apt_get: true

    - name: Installation de grafana
      apt:
        name: grafana
