- become: yes
  hosts: all
  name: grafana-install

  vars:
    dependances:
      - apt-transport-https
      - software-properties-common
      - wget
      - ca-certificates
      - libfontconfig
      - gnupg
      - gnupg1
      - gnupg2

  tasks:
    - name: Création de l'utilisateur Grafana
      user:
        name: grafana
        group: sudo

    - name: Installation des dépendances
      apt:
        name: "{{ item }}"
      loop: "{{ dependances }}"

    - name: Importation clé GPG de Grafana
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present
        validate_certs: false

    - name: Ajout du dépôt de Grafana
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: true

    - name: Installation de grafana
      apt:
        name: grafana

    - name: Activation du service Grafana au démarre de l'instance
      systemd:
        name: grafana-server
        enabled: true
        state: started
        daemon_reload: true

    - name: Importation clé GPG de InfluxDB
      apt_key:
        url: "https://repos.influxdata.com/influxdb.key"
        state: present
        validate_certs: false

    - name: Ajout du dépôt de InfluxDB
      apt_repository:
        repo: deb https://repos.influxdata.com/ubuntu/ focal stable
        state: present
        update_cache: true

    - name: Installation de InfluxDB
      apt:
        name: influxdb

    - name: Activation du service InfluxDB au démarre de l'instance
      systemd:
        name: influxdb
        enabled: true
        state: started
        daemon_reload: true


