- become: yes
  hosts: all
  name: grafana-install

  vars:
    dependances:
      - apt-transport-https
      - software-properties-common
      - wget
      - ca-certificates
      - libfontconfig
      - python3
      - python3-dev
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev jq
      - apache2
      - libapache2-mod-php
  vars:
    python:
      - jinja2
      - PyYAML
      - paramiko
      - cryptography
      - packaging
      - python3

  tasks:
    - name: Création de l'utilisateur Nextcloud
      user:
        name: nextcloud
        group: sudo

    - name: Installation des dépendances system
      apt:
        name: "{{ item }}"
      loop: "{{ dependances }}"

    - name: Installation des dépendances Python
      pip:
        name: "{{ item }}"
      loop: "{{ python }}"

    - name: Telecharger Nextcloud via wget
      wget:
        repo: https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
        state: present
        update_cache: true

    - name: Telecharger Nextcloud via wget
      wget:
        repo: https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
        state: present
        update_cache: true

    - name: Unzip Nexcloud
      ansible.builtin.unarchive:
        src: nextcloud-21.0.1.zip

    - name: Deplacer Nextcloud dans /var/www/html
      command: mv nextcloud /var/www/html

    - name: Privileges
      command: chown -R www-data:www-data /var/www/html/nextcloud/ | chmod -R 755 /var/www/html/nextcloud/

    - name: Copie la conf pour NC depuis la machine local
      copy:
        src: /terraform/TP3-Cloud/Conf_Apache_NC/nextcloud.conf
        dest: /etc/apache2/sites-available/nextcloud.conf
        backup: yes

    - name: Activez host virtuel Apache et les modules requis
      shell: |
        a2ensite nextcloud.conf
        a2enmod rewrite
        a2enmod headers
        a2enmod env
        a2enmod dir
        a2enmod mime

    - name: Activez host virtuel Apache et les modules requis
      shell: |
        systemctl restart apache2
