- become: yes
  hosts: all
  name: grafana-install

  vars:
    dependances:
      - apt-transport-https
      - software-properties-common
      - wget
      - ca-certificates
      - libfontconfig
      - build-essential
      - libssl-dev
      - apache2
      - libapache2-mod-php
      - unzip
      - php-gd
      - php-mysql
      - php-curl
      - php-mbstring
      - php-gd
      - php-mbstring
      - php-intl
      - php-gmp
      - php-bcmath
      - php-imagick
      - php-xml
      - php-zip
    nextcloud_verison: "21.0.1"
    nextcloud_db: "mysql"
    nextcloud_db_host: "192.168.1.254:3306"
    nextcloud_db_name: "nextcloud_db"
    nextcloud_db_admin: "DBAdmin"
    nextcloud_db_pwd: "Epsi2022!DB"
    nextcloud_admin_name: "NCAdmin"
    nextcloud_admin_pwd: "Epsi2022!NC"
    nextcloud_data_dir: "/data"
    nextcloud_webroot: "/var/www/html/nextcloud/"
    nextcloud_trusted_domain: 
      - "{{ ansible_default_ipv4.address }}"
      - "{{ ansible_fqdn }}"



  tasks:
    - name: Création de l'utilisateur Nextcloud
      user:
        name: nextcloud
        group: sudo

    - name: Installation des dépendances
      apt:
        name: "{{ item }}"
      loop: "{{ dependances }}"

    - name: Telecharger Nextcloud
      unarchive:
        src: https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_verison }}.zip
        dest: /tmp/
        remote_src: yes
        validate_certs: false

    - name: Deplacer Nextcloud dans /var/www/html
      command: mv /tmp/nextcloud /var/www/html

    - name: Création du dossier data pour Nextlcoud
      command: mkdir {{ nextcloud_data_dir }}

    - name: Privileges
      shell: |
       chown -R www-data:www-data {{ nextcloud_webroot }}
       chmod -R 755 {{ nextcloud_webroot }}

    - name: Copie la conf pour NC depuis la machine local
      copy:
        src: ./Conf_Apache_NC/nextcloud.conf
        dest: /etc/apache2/sites-available/nextcloud.conf
        backup: yes

    - name: Activez host virtuel Apache et les modules requis
      shell: |
        a2ensite nextcloud.conf
        a2enmod rewrite
        a2enmod headers
        a2enmod env
        a2enmod dir
        a2enmod mime

    - name: Activez host virtuel Apache et les modules requis
      shell: |
        systemctl restart apache2

    - name: "Ajout du disque supplémentaire 1/3"
      parted:
        device: /dev/vdb
        number: 1
        flags: [ lvm ]
        state: present

    - name: "Ajout du disque supplémentaire 2/3"
      filesystem:
        fstype: ext4
        dev: /dev/vdb1
    
    - name: "Ajout du disque supplémentaire 3/3"
      mount:
        fstype: ext4
        src: /dev/vdb1
        path: "{{ nextcloud_data_dir }}"
        state: mounted

    - name: "Ajout de la configuration de la base de données"
      command: >
        php occ maintenance:install
        --database={{ nextcloud_db }}
        --database-host={{ nextcloud_db_host }}
        --database-name={{ nextcloud_db_name }}
        --database-user={{ nextcloud_db_admin }}
        --database-pass={{ nextcloud_db_pwd }}
        --admin-user={{ nextcloud_admin_name }}
        --admin-pass={{ nextcloud_admin_pwd }}
        --data-dir={{ nextcloud_data_dir }}
      args:
        chdir: "{{ nextcloud_webroot }}"
        creates: "{{ nextcloud_webroot }}/config/config.php"

    - name: "Ajout du trusted domain Nextlcoud"
      command: php occ config:system:set trusted_domains {{ item.0 }} --value="{{ item.1 | ipwrap }}"
      args:
        chdir: "{{ nextcloud_webroot }}"
      with_indexed_items: "{{ nextcloud_trusted_domain }}"

    - name: "Changement des droits"
      shell: |
        chown -R www-data:www-data {{ nextcloud_webroot }}
        chmod -R 755 {{ nextcloud_webroot }}
        chown -R www-data:www-data {{ nextcloud_data_dir}}
        chmod -R 755 {{ nextcloud_data-dir }}
      