- become: yes
  hosts: all
  name: grafana-install

  vars:
    dependances:
      - apt-transport-https
      - software-properties-common
      - wget
      - ca-certificates
      - libfontconfig
      - build-essential
      - libssl-dev
      - apache2
      - libapache2-mod-php
      - unzip
      - php-gd
      - php-mysql
      - php-curl
      - php-mbstring
      - php-gd
      - php-mbstring
      - php-intl
      - php-gmp
      - php-bcmath
      - php-imagick
      - php-xml
      - php-zip

  tasks:
    - name: Création de l'utilisateur Nextcloud
      user:
        name: nextcloud
        group: sudo

    - name: Installation des dépendances
      apt:
        name: "{{ item }}"
      loop: "{{ dependances }}"

    - name: Telecharger Nextcloud
      unarchive:
        src: https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
        dest: /tmp/
        remote_src: yes
        validate_certs: false

    - name: Deplacer Nextcloud dans /var/www/html
      command: mv /tmp/nextcloud /var/www/html

    - name: Privileges
      shell: |
       chown -R www-data:www-data /var/www/html/nextcloud/
       chmod -R 755 /var/www/html/nextcloud/

    - name: Copie la conf pour NC depuis la machine local
      copy:
        src: ./Conf_Apache_NC/nextcloud.conf
        dest: /etc/apache2/sites-available/nextcloud.conf
        backup: yes

    - name: Activez host virtuel Apache et les modules requis
      shell: |
        a2ensite nextcloud.conf
        a2enmod rewrite
        a2enmod headers
        a2enmod env
        a2enmod dir
        a2enmod mime

    - name: Activez host virtuel Apache et les modules requis
      shell: |
        systemctl restart apache2
