version: '3.8'

services:
  app:
    image: nextcloud:23.0-apache
    networks:
      - nextcloud
      # - traefik-net
    volumes:
      - nextcloud:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "20"
    # depends_on:
    #   - db
    # deploy:
    #   replicas: 1
    #   labels:
    #     - traefik.enable=true
    #     - traefik.docker.network=traefik-net
    #     - traefik.http.services.nextcloud.loadbalancer.server.port=80
    #     - traefik.http.routers.nextcloud.rule=Host(`nextcloud.si.consertotech.pro`)

# networks:
#   nextcloud: {}
#   traefik-net:
#     external: true

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_DIR}/db
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_DIR}/data
